"""Pydantic models for agent typed IO.

All agent boundaries are Pydantic-typed per architecture §2.3.
Free-form text outside the typed schema is rejected.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class IssueContext(BaseModel):
    """Input context for the single-agent (and Planner) topology.

    Contains the issue text, repo metadata, and optional RAG/episodic hits.
    """

    repo_url: str = Field(..., min_length=1, description="Canonical GitHub repo URL")
    issue_number: int = Field(..., gt=0, description="GitHub issue number")
    issue_text: str = Field(..., min_length=1, description="Issue title + body")
    repo_files: dict[str, str] = Field(
        default_factory=dict,
        description="Map of file_path -> file_content for repo context",
    )
    repo_facts: list[dict[str, str]] = Field(
        default_factory=list,
        description="Episodic repo_facts for this repo_url",
    )


class ChangePlan(BaseModel):
    """Typed output for planning step — file-level edit plan.

    Architecturally equivalent to the Planner agent output (VAL-PLANNER-001),
    but used internally by the single_agent topology as a structured
    intermediate step.
    """

    target_files: list[str] = Field(
        ..., min_length=1, description="Files to modify"
    )
    rationale: str = Field(
        ..., min_length=20, description="Why these changes are needed"
    )
    approach: str = Field(
        default="", description="Suggested implementation approach"
    )


class CodeEdit(BaseModel):
    """Typed output for code editing step.

    Contains the unified diff and list of touched files.
    """

    diff: str = Field(..., min_length=1, description="Unified diff to apply")
    touched_files: list[str] = Field(
        ..., min_length=1, description="Files modified by this diff"
    )
    diff_hash: str = Field(
        default="", description="SHA-256 of canonicalized diff for loop detection"
    )


class TestReport(BaseModel):
    """Typed output for test execution step.

    Reports pass/fail counts, failed test names, and generated test files.
    """

    passed: int = Field(..., ge=0, description="Number of passing tests")
    failed: int = Field(..., ge=0, description="Number of failing tests")
    failed_test_names: list[str] = Field(
        default_factory=list, description="Names of failing tests"
    )
    generated_test_files: list[str] = Field(
        default_factory=list, description="Test files generated by the agent"
    )


class ReviewResult(BaseModel):
    """Typed output for review step.

    Verdict must be one of: accept, reject_with_changes, reject.
    """

    verdict: str = Field(
        ...,
        description="One of: accept, reject_with_changes, reject",
    )
    issues: list[str] = Field(
        default_factory=list,
        description="List of issues found during review",
    )


class SingleAgentOutput(BaseModel):
    """Final output of the single-agent topology.

    The single agent produces this typed output containing:
    - The plan it devised
    - The code edit it made
    - The test report from running tests
    - Whether it's ready for PR
    """

    plan: ChangePlan = Field(..., description="The change plan")
    code_edit: CodeEdit = Field(..., description="The code edit applied")
    test_report: TestReport = Field(..., description="Test execution results")
    ready_for_pr: bool = Field(
        default=False, description="Whether the changes are ready for PR"
    )
    summary: str = Field(
        default="", description="Human-readable summary of what was done"
    )
