"""Pydantic models for agent typed IO.

All agent boundaries are Pydantic-typed per architecture §2.3.
Free-form text outside the typed schema is rejected.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator


class RAGHit(BaseModel):
    """A single RAG retrieval result from pgvector semantic store.

    Each hit includes the file path, the chunk text, and the
    similarity score.  Results are scoped by repo_url in the
    retrieval query (VAL-PLANNER-003).
    """

    file_path: str = Field(..., min_length=1, description="Source file path")
    chunk_text: str = Field(..., min_length=1, description="Chunk content")
    score: float = Field(default=0.0, description="Cosine similarity score")


class EpisodicFact(BaseModel):
    """A single episodic fact from the repo_facts table.

    Used by the Planner to incorporate prior knowledge about
    the target repo (VAL-PLANNER-004).
    """

    fact_kind: str = Field(..., description="Category of the fact")
    fact_value: dict[str, object] = Field(
        default_factory=dict, description="Fact payload"
    )


class IssueContext(BaseModel):
    """Input context for the Planner (and single-agent) topology.

    Contains the issue text, repo metadata, RAG hits from pgvector,
    and episodic memory hits from the repo_facts/decisions/outcomes
    tables (VAL-PLANNER-003, VAL-PLANNER-004).
    """

    repo_url: str = Field(..., min_length=1, description="Canonical GitHub repo URL")
    issue_number: int = Field(..., gt=0, description="GitHub issue number")
    issue_text: str = Field(..., min_length=1, description="Issue title + body")
    repo_files: dict[str, str] = Field(
        default_factory=dict,
        description="Map of file_path -> file_content for repo context",
    )
    repo_facts: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Episodic repo_facts for this repo_url",
    )
    rag_hits: list[RAGHit] = Field(
        default_factory=list,
        description="RAG retrieval results from pgvector scoped to repo_url",
    )
    episodic_facts: list[EpisodicFact] = Field(
        default_factory=list,
        description="Episodic facts from repo_facts table for this repo_url",
    )
    recent_decisions: list[dict[str, object]] = Field(
        default_factory=list,
        description="Recent decisions for this repo_url from episodic store",
    )


class ChangePlan(BaseModel):
    """Typed output for planning step — file-level edit plan.

    Architecturally equivalent to the Planner agent output (VAL-PLANNER-001),
    but used internally by the single_agent topology as a structured
    intermediate step.

    The rationale field is validated to be at least 20 characters
    (VAL-PLANNER-007).  Free-form text outside this schema is
    rejected by the PydanticAI output parser (VAL-PLANNER-005).
    """

    target_files: list[str] = Field(
        ..., min_length=1, description="Files to modify"
    )
    rationale: str = Field(
        ..., min_length=20, description="Why these changes are needed"
    )
    approach: str = Field(
        default="", description="Suggested implementation approach"
    )
    estimated_complexity: str = Field(
        default="medium",
        description="Estimated complexity: low, medium, or high",
    )

    @field_validator("rationale")
    @classmethod
    def _rationale_not_whitespace(cls, v: str) -> str:
        """Rationale must contain at least one non-whitespace character."""
        if not v.strip():
            msg = "Rationale must not be empty or whitespace-only"
            raise ValueError(msg)
        return v


class CodeEdit(BaseModel):
    """Typed output for code editing step.

    Contains the unified diff and list of touched files.
    """

    diff: str = Field(..., min_length=1, description="Unified diff to apply")
    touched_files: list[str] = Field(
        ..., min_length=1, description="Files modified by this diff"
    )
    diff_hash: str = Field(
        default="", description="SHA-256 of canonicalized diff for loop detection"
    )


class TestReport(BaseModel):
    """Typed output for test execution step.

    Reports pass/fail counts, failed test names, and generated test files.

    VAL-QA-006: ``failed_test_names`` length must equal ``failed``.
    A TestReport with ``failed=2`` and ``failed_test_names=[]`` fails
    validation.
    """

    __test__ = False  # Prevent pytest from trying to collect this as a test class

    passed: int = Field(..., ge=0, description="Number of passing tests")
    failed: int = Field(..., ge=0, description="Number of failing tests")
    failed_test_names: list[str] = Field(
        default_factory=list, description="Names of failing tests"
    )
    generated_test_files: list[str] = Field(
        default_factory=list, description="Test files generated by the agent"
    )

    @field_validator("failed_test_names")
    @classmethod
    def _failed_names_matches_count(cls, v: list[str], info: Any) -> list[str]:
        """Enforce that len(failed_test_names) == failed (VAL-QA-006).

        A TestReport with failed=2 and failed_test_names=[] fails validation.
        This ensures the failed count always matches the list of named failures.
        """
        # During validation, 'failed' may not be set yet if fields are
        # validated in order.  We check using validation data if available.
        failed_val: int | None = None
        if info.data and "failed" in info.data:
            failed_val = info.data["failed"]
        if failed_val is not None and len(v) != failed_val:
            msg = (
                f"failed_test_names length ({len(v)}) must equal "
                f"failed count ({failed_val})"
            )
            raise ValueError(msg)
        return v

    @model_validator(mode="after")
    def _validate_failed_names_after(self) -> TestReport:
        """Cross-field validation: failed_test_names length must match failed.

        This runs AFTER all field validators, so both 'failed' and
        'failed_test_names' are guaranteed to be set.
        """
        if len(self.failed_test_names) != self.failed:
            msg = (
                f"failed_test_names length ({len(self.failed_test_names)}) "
                f"must equal failed count ({self.failed})"
            )
            raise ValueError(msg)
        return self


class ReviewResult(BaseModel):
    """Typed output for review step.

    Verdict must be one of: accept, reject_with_changes, reject.
    Using Literal enforces the enum at the Pydantic level so that
    any out-of-enum value (e.g. "lgtm", "approved") fails validation
    and counts toward the retry budget (VAL-REVIEWER-002).
    """

    verdict: Literal["accept", "reject_with_changes", "reject"] = Field(
        ...,
        description="One of: accept, reject_with_changes, reject",
    )
    issues: list[str] = Field(
        default_factory=list,
        description="List of issues found during review",
    )
    diff_hash: str = Field(
        default="",
        description="SHA-256 hash of the CodeEdit diff being reviewed, "
        "for same-fix rejection tracking",
    )


class SingleAgentOutput(BaseModel):
    """Final output of the single-agent topology.

    The single agent produces this typed output containing:
    - The plan it devised
    - The code edit it made
    - The test report from running tests
    - Whether it's ready for PR
    """

    plan: ChangePlan = Field(..., description="The change plan")
    code_edit: CodeEdit = Field(..., description="The code edit applied")
    test_report: TestReport = Field(..., description="Test execution results")
    ready_for_pr: bool = Field(
        default=False, description="Whether the changes are ready for PR"
    )
    summary: str = Field(
        default="", description="Human-readable summary of what was done"
    )
